// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0-B2lNyJF91pY2TshpnG265GxQC7d7Gk',
    appId: '1:956714113383:web:52b8e8484896fd7a4e77c2',
    messagingSenderId: '956714113383',
    projectId: 'sportify-flutter-bc070',
    authDomain: 'sportify-flutter-bc070.firebaseapp.com',
    storageBucket: 'sportify-flutter-bc070.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuQnRXpoGAi2nBjqUNbbRFgKw0KMadSIs',
    appId: '1:956714113383:android:e98514709d9fcca14e77c2',
    messagingSenderId: '956714113383',
    projectId: 'sportify-flutter-bc070',
    storageBucket: 'sportify-flutter-bc070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjJfnFmdLExI9LkwuDSRV0BRbwIkiQiHc',
    appId: '1:956714113383:ios:e28e0c611253a97f4e77c2',
    messagingSenderId: '956714113383',
    projectId: 'sportify-flutter-bc070',
    storageBucket: 'sportify-flutter-bc070.appspot.com',
    iosBundleId: 'com.example.ahmetUygunEindproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjJfnFmdLExI9LkwuDSRV0BRbwIkiQiHc',
    appId: '1:956714113383:ios:ff275053387b33f24e77c2',
    messagingSenderId: '956714113383',
    projectId: 'sportify-flutter-bc070',
    storageBucket: 'sportify-flutter-bc070.appspot.com',
    iosBundleId: 'com.example.ahmetUygunEindproject.RunnerTests',
  );
}
